export const FICHA_DEUDOR_PANEL = {
  DATOS_ADICIONALES: 'DATOS ADICIONALES',
  TELEFONOS_REFERENCIADOS: 'TELÉFONOS REFERENCIADOS',
  DIRECCIONES_REFERENCIADAS: 'DIRECCIONES REFERENCIADAS',
  GESTION_REALIZADA: 'GESTIÓN REALIZADA',
  ESTADO_GESTION_REALIZADA: 'ESTADO DE GESTIÓN REALIZADA',
} as const;

export type FichaDeudorPanel =
  (typeof FICHA_DEUDOR_PANEL)[keyof typeof FICHA_DEUDOR_PANEL];

export const FICHA_DEUDOR_PANEL_OPTIONS = [
  FICHA_DEUDOR_PANEL.DATOS_ADICIONALES,
  FICHA_DEUDOR_PANEL.TELEFONOS_REFERENCIADOS,
  FICHA_DEUDOR_PANEL.DIRECCIONES_REFERENCIADAS,
  FICHA_DEUDOR_PANEL.GESTION_REALIZADA,
  FICHA_DEUDOR_PANEL.ESTADO_GESTION_REALIZADA,
] as const;